# Maintained by baxvis (Jovan Bogovac)
# https://github.com/baxvis/dotfiles

set-option -g default-shell /usr/bin/zsh
set-option -g default-command /usr/bin/zsh
set-option -g default-terminal "xterm-kitty"
set-option -s escape-time 0
unbind ^B
set-option -g prefix ^F
set-option -g status-style bg=default
set-option -g message-style bg=default
set-option -g message-command-style bg=default
set-option -g message-command-style bg=default
set-option -g window-style bg=default
set-option -g pane-active-border-style bg=default
set -g history-limit 100000
set-window-option -g mode-keys vi
set -g mode-style "reverse"
