# #######################################################################################
# Maintained by baxvis (Jovan Bogovac)
# https://github.com/baxvis/dotfiles
# #######################################################################################

# BACKGROUND
background {
    monitor =
    path = ~/.config/hypr/assets/wallpaper.jpg
    blur_passes = 3
    contrast = 0.92
    brightness = 0.85
    vibrancy = 0.2
    vibrancy_darkness = 0.05
}

# General
general {
}

# Time
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +'%H:%M')"
    color = rgba(255, 255, 255, 0.85)
    font_size = 110
    font_family = Hack Regular
    position = 0, 300
    halign = center
    valign = center
}

# Day of week
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +'%A')"
    color = rgba(255, 255, 255, 0.7)
    font_size = 30
    font_family = Hack Regular
    position = 0, 180
    halign = center
    valign = center
}

# Date
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +'%d %B %Y')"
    color = rgba(255, 255, 255, 0.65)
    font_size = 26
    font_family = Hack Regular
    position = 0, 140
    halign = center
    valign = center
}

# Username
shape {
    monitor =
    size = 450, 90
    color = rgba(0, 255, 255, 0.12)
    rounding = 50
    border_size = 1
    border_color = rgba(255, 255, 255, 0.15)
    rotate = 0
    xray = false
    position = 0, -40
    halign = center
    valign = center
}

# Username label
label {
    monitor =
    text =  $USER
    color = rgba(255, 255, 255, 0.85)
    font_size = 30
    font_family = Hack Regular
    position = 0, -40
    halign = center
    valign = center
}

# Password input field
input-field {
    monitor =
    size = 450, 90
    outline_thickness = 0
    dots_size = 0.25
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(0, 255, 255, 0.12)
    font_color = rgba(255, 255, 255, 0.9)
    fade_on_empty = false
    font_family = Hack Regular
    placeholder_text = Enter your password
    hide_input = false
    position = 0, -160
    halign = center
    valign = center
    capslock_color = rgba(0, 255, 255, 0.4)
    fail_color = rgba(255, 85, 85, 0.8)
}

# Bottom buttons

# Power Off
label {
    monitor =
    text = 󰐥
    color = rgba(255, 255, 255, 0.6)
    font_size = 40
    onclick = shutdown now
    position = -200, 80
    halign = center
    valign = bottom
}

# Reboot
label {
    monitor =
    text = 󰜉
    color = rgba(255, 255, 255, 0.6)
    font_size = 40
    onclick = reboot now
    position = 0, 80
    halign = center
    valign = bottom
}

# Suspend
label {
    monitor =
    text = 󰤄
    color = rgba(255, 255, 255, 0.6)
    font_size = 40
    onclick = systemctl suspend
    position = 200, 80
    halign = center
    valign = bottom
}
